package catalog

import (
	"fmt"
	"strings"
)

// RenderManifest produces the YAML content for <modelsdir>/<name>/manifest.yaml,
// matching the schema parsed by internal/registry.Manifest. The output is built
// explicitly (not via a yaml marshaller) so the file is readable and only emits
// the fields that are actually set for the entry.
func (e Entry) RenderManifest() string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by `visionserve pull %s` — do not hand-edit blindly.\n", e.Name)
	if e.Description != "" {
		fmt.Fprintf(&b, "# %s\n", e.Description)
	}
	if !e.Verified {
		fmt.Fprintf(&b, "# WARNING: pulled from an unverified HF source. %s\n", e.Note)
	}
	fmt.Fprintf(&b, "name: %s\n", e.Name)
	fmt.Fprintf(&b, "task: %s\n", e.Task)
	fmt.Fprintf(&b, "license: %s\n", e.License)
	if e.Architecture != "" {
		fmt.Fprintf(&b, "architecture: %s\n", e.Architecture)
	}

	// model_file (single-file) vs files: map (multi-session).
	manifestFiles := e.manifestFiles()
	if len(manifestFiles) > 0 {
		b.WriteString("\nfiles:\n")
		for _, f := range manifestFiles {
			fmt.Fprintf(&b, "  %s: %s\n", f.ManifestRole, f.LocalFilename)
		}
	} else if mf := e.modelFile(); mf != "" {
		fmt.Fprintf(&b, "model_file: %s\n", mf)
	}

	// input block.
	b.WriteString("\ninput:\n")
	fmt.Fprintf(&b, "  width: %d\n", e.InputWidth)
	fmt.Fprintf(&b, "  height: %d\n", e.InputHeight)
	if e.InputLayout != "" {
		fmt.Fprintf(&b, "  layout: %s\n", e.InputLayout)
	}
	fmt.Fprintf(&b, "  letterbox: %t\n", e.Letterbox)
	if e.Normalize != nil {
		b.WriteString("  normalize:\n")
		fmt.Fprintf(&b, "    mean: %s\n", floatList(e.Normalize.Mean))
		fmt.Fprintf(&b, "    std: %s\n", floatList(e.Normalize.Std))
	}

	// postprocess block.
	b.WriteString("\npostprocess:\n")
	fmt.Fprintf(&b, "  type: %s\n", e.PostprocessType)
	if e.BoxFormat != "" {
		fmt.Fprintf(&b, "  box_format: %s\n", e.BoxFormat)
	}
	if e.ConfThreshold > 0 {
		fmt.Fprintf(&b, "  conf_threshold: %g\n", e.ConfThreshold)
	}
	if e.TextThreshold > 0 {
		fmt.Fprintf(&b, "  text_threshold: %g\n", e.TextThreshold)
	}
	if e.MaxDetections > 0 {
		fmt.Fprintf(&b, "  max_detections: %d\n", e.MaxDetections)
	}

	if e.LabelsFile != "" {
		fmt.Fprintf(&b, "\nlabels: %s\n", e.LabelsFile)
	}

	// runtime block.
	if len(e.RuntimePrefer) > 0 || e.IdleUnloadSeconds > 0 {
		b.WriteString("\nruntime:\n")
		if len(e.RuntimePrefer) > 0 {
			fmt.Fprintf(&b, "  prefer: [%s]\n", strings.Join(e.RuntimePrefer, ", "))
		}
		if e.IdleUnloadSeconds > 0 {
			fmt.Fprintf(&b, "  idle_unload_seconds: %d\n", e.IdleUnloadSeconds)
		}
	}

	return b.String()
}

// manifestFiles returns the files that should appear in the manifest `files:` map.
func (e Entry) manifestFiles() []File {
	var out []File
	for _, f := range e.Files {
		if f.ManifestRole != "" {
			out = append(out, f)
		}
	}
	return out
}

// modelFile returns the single model_file local name when the entry is
// single-session (exactly one file, no ManifestRole used).
func (e Entry) modelFile() string {
	if len(e.manifestFiles()) > 0 {
		return ""
	}
	for _, f := range e.Files {
		if f.Role == "model" {
			return f.LocalFilename
		}
	}
	if len(e.Files) == 1 {
		return e.Files[0].LocalFilename
	}
	return ""
}

func floatList(xs []float32) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%g", x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
