package catalog

import (
	"fmt"
	"sort"
	"strings"
)

// generatedHeader opens every manifest RenderManifest writes. Pull uses it to tell a manifest it
// generated (safe to regenerate when the catalog changes) from one a user wrote or edited.
const generatedHeader = "# Generated by `visionserve pull"

// RenderManifest produces the YAML content for <modelsdir>/<name>/manifest.yaml,
// matching the schema parsed by internal/registry.Manifest. The output is built
// explicitly (not via a yaml marshaller) so the file is readable and only emits
// the fields that are actually set for the entry.
func (e Entry) RenderManifest() string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s %s` — do not hand-edit blindly.\n", generatedHeader, e.Name)
	if e.Description != "" {
		fmt.Fprintf(&b, "# %s\n", e.Description)
	}
	if !e.Verified {
		fmt.Fprintf(&b, "# WARNING: pulled from an unverified HF source. %s\n", e.Note)
	}
	fmt.Fprintf(&b, "name: %s\n", e.Name)
	fmt.Fprintf(&b, "task: %s\n", e.Task)
	fmt.Fprintf(&b, "license: %s\n", e.License)
	// source_url and sha256 are what turn "the manifest says Apache-2.0" into "these exact
	// bytes came from this audited upstream". The registry's verified mode refuses a model
	// missing either, so a pulled model has to carry both to be usable there.
	if src := e.SourceURL(); src != "" {
		fmt.Fprintf(&b, "source_url: %s\n", src)
	}
	b.WriteString(e.renderSHA256())
	if e.Architecture != "" {
		fmt.Fprintf(&b, "architecture: %s\n", e.Architecture)
	}
	if e.Detector != "" {
		fmt.Fprintf(&b, "detector: %s\n", e.Detector)
	}
	if e.Segmenter != "" {
		fmt.Fprintf(&b, "segmenter: %s\n", e.Segmenter)
	}

	// model_file (single-file) vs files: map (multi-session or virtual).
	if len(e.VirtualFiles) > 0 {
		// Virtual pipeline model: paths reference sibling model directories.
		b.WriteString("\nfiles:\n")
		roles := make([]string, 0, len(e.VirtualFiles))
		for k := range e.VirtualFiles {
			roles = append(roles, k)
		}
		sort.Strings(roles)
		for _, role := range roles {
			fmt.Fprintf(&b, "  %s: %s\n", role, e.VirtualFiles[role])
		}
	} else if manifestFiles := e.manifestFiles(); len(manifestFiles) > 0 {
		b.WriteString("\nfiles:\n")
		for _, f := range manifestFiles {
			fmt.Fprintf(&b, "  %s: %s\n", f.ManifestRole, f.LocalFilename)
		}
	} else if mf := e.modelFile(); mf != "" {
		fmt.Fprintf(&b, "model_file: %s\n", mf)
	}

	// input block.
	b.WriteString("\ninput:\n")
	fmt.Fprintf(&b, "  width: %d\n", e.InputWidth)
	fmt.Fprintf(&b, "  height: %d\n", e.InputHeight)
	if e.InputLayout != "" {
		fmt.Fprintf(&b, "  layout: %s\n", e.InputLayout)
	}
	fmt.Fprintf(&b, "  letterbox: %t\n", e.Letterbox)
	if e.Normalize != nil {
		b.WriteString("  normalize:\n")
		fmt.Fprintf(&b, "    mean: %s\n", floatList(e.Normalize.Mean))
		fmt.Fprintf(&b, "    std: %s\n", floatList(e.Normalize.Std))
	}

	// postprocess block (embedding towers have none).
	if e.PostprocessType != "" || e.ConfThreshold > 0 || e.MaxDetections > 0 {
		b.WriteString("\npostprocess:\n")
		fmt.Fprintf(&b, "  type: %s\n", e.PostprocessType)
	}
	if e.BoxFormat != "" {
		fmt.Fprintf(&b, "  box_format: %s\n", e.BoxFormat)
	}
	if e.ConfThreshold > 0 {
		fmt.Fprintf(&b, "  conf_threshold: %g\n", e.ConfThreshold)
	}
	if e.TextThreshold > 0 {
		fmt.Fprintf(&b, "  text_threshold: %g\n", e.TextThreshold)
	}
	if e.MaxDetections > 0 {
		fmt.Fprintf(&b, "  max_detections: %d\n", e.MaxDetections)
	}

	// grasp block (only when gripper bounds are set).
	if e.GripperMin > 0 || e.GripperMax > 0 {
		b.WriteString("\ngrasp:\n")
		if e.GripperMin > 0 {
			fmt.Fprintf(&b, "  gripper_min: %g\n", e.GripperMin)
		}
		if e.GripperMax > 0 {
			fmt.Fprintf(&b, "  gripper_max: %g\n", e.GripperMax)
		}
	}

	// explain block (only when configured).
	if e.Explain != nil {
		b.WriteString("\nexplain:\n")
		fmt.Fprintf(&b, "  type: %s\n", e.Explain.Type)
		if len(e.Explain.Outputs) > 0 {
			b.WriteString("  outputs:\n")
			// emit in sorted order for determinism
			keys := make([]string, 0, len(e.Explain.Outputs))
			for k := range e.Explain.Outputs {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				fmt.Fprintf(&b, "    %s: %s\n", k, e.Explain.Outputs[k])
			}
		}
		if e.Explain.SpatialStride > 0 {
			fmt.Fprintf(&b, "  spatial_stride: %d\n", e.Explain.SpatialStride)
		}
		if e.Explain.TopChannels > 0 {
			fmt.Fprintf(&b, "  top_channels: %d\n", e.Explain.TopChannels)
		}
	}

	// instance block (only when configured).
	if e.Instance != nil {
		b.WriteString("\ninstance:\n")
		if e.Instance.MaxTemplates > 0 {
			fmt.Fprintf(&b, "  max_templates: %d\n", e.Instance.MaxTemplates)
		}
		if e.Instance.SimThreshold > 0 {
			fmt.Fprintf(&b, "  sim_threshold: %g\n", e.Instance.SimThreshold)
		}
		if e.Instance.PatchSize > 0 {
			fmt.Fprintf(&b, "  patch_size: %d\n", e.Instance.PatchSize)
		}
	}

	if e.LabelsFile != "" {
		fmt.Fprintf(&b, "\nlabels: %s\n", e.LabelsFile)
	}

	// runtime block.
	if len(e.RuntimePrefer) > 0 || e.IdleUnloadSeconds > 0 {
		b.WriteString("\nruntime:\n")
		if len(e.RuntimePrefer) > 0 {
			fmt.Fprintf(&b, "  prefer: [%s]\n", strings.Join(e.RuntimePrefer, ", "))
		}
		if e.IdleUnloadSeconds > 0 {
			fmt.Fprintf(&b, "  idle_unload_seconds: %d\n", e.IdleUnloadSeconds)
		}
	}

	return b.String()
}

// SourceURL is the audited upstream this entry's weights come from. Derived rather than
// stored, so it cannot drift from HFRepo. The trailing slash matters: registry's ledger and
// verified-source allowlist both match by URL prefix, and the ledger records repo roots in
// exactly this form. Entries served from DirectURL have no single canonical repo page, so
// they get no source_url and stay outside verified mode until one is recorded by hand.
func (e Entry) SourceURL() string {
	if e.HFRepo == "" {
		return ""
	}
	return "https://huggingface.co/" + e.HFRepo + "/"
}

// renderSHA256 emits the manifest `sha256:` field, or "" when nothing is pinned. The shape
// mirrors what registry.SHA256Field parses: a scalar for a single-file model, a role→digest
// map for a multi-session one. Side files that carry no ManifestRole (a vocab, say) are not
// in the manifest's `files:` map and so cannot be pinned there — Pull still verifies them
// against the catalog.
func (e Entry) renderSHA256() string {
	if len(e.VirtualFiles) > 0 {
		return "" // composed model: the pins live in the dependencies it references
	}
	if mf := e.modelFile(); mf != "" {
		for _, f := range e.Files {
			if f.LocalFilename == mf && f.SHA256 != "" {
				return fmt.Sprintf("sha256: %s\n", f.SHA256)
			}
		}
		return ""
	}
	var pinned []File
	for _, f := range e.manifestFiles() {
		if f.SHA256 != "" {
			pinned = append(pinned, f)
		}
	}
	if len(pinned) == 0 {
		return ""
	}
	sort.Slice(pinned, func(i, j int) bool { return pinned[i].ManifestRole < pinned[j].ManifestRole })
	var b strings.Builder
	b.WriteString("sha256:\n")
	for _, f := range pinned {
		fmt.Fprintf(&b, "  %s: %s\n", f.ManifestRole, f.SHA256)
	}
	return b.String()
}

// manifestFiles returns the files that should appear in the manifest `files:` map.
func (e Entry) manifestFiles() []File {
	var out []File
	for _, f := range e.Files {
		if f.ManifestRole != "" {
			out = append(out, f)
		}
	}
	return out
}

// modelFile returns the single model_file local name when the entry is
// single-session (exactly one file, no ManifestRole used).
func (e Entry) modelFile() string {
	if len(e.manifestFiles()) > 0 {
		return ""
	}
	for _, f := range e.Files {
		if f.Role == "model" {
			return f.LocalFilename
		}
	}
	if len(e.Files) == 1 {
		return e.Files[0].LocalFilename
	}
	return ""
}

func floatList(xs []float32) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%g", x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
