"""Generate postprocess_sync.json: shared cases for the robot / grasp helpers, computed by the
Python SDK (clients/python/visionserve/postprocess.py, Grasp in types.py).

The JS SDK ports the same helpers (clients/js/src/postprocess.ts) and runs these cases in
clients/js/tests/postprocess.test.ts; clients/python/tests/test_postprocess_sync.py checks that the
Python code still gives what this file says. Regenerate after changing the maths on purpose:

    PYTHONPATH=clients/python python3 clients/testdata/gen_postprocess_sync.py
"""

import json
import math
from pathlib import Path

import numpy as np

from visionserve.postprocess import (
    CameraIntrinsics,
    backproject,
    camera_distance,
    get_depth_at_detection,
    grasp_distances,
    object_distances,
    select_target_grasp,
    select_target_object,
)
from visionserve.types import Grasp, Result

W, H = 8, 6
# uint16 millimetres; 0 = no reading.
MM = [[1000 + 37 * x + 53 * y for x in range(W)] for y in range(H)]
for x, y in [(0, 0), (1, 0), (5, 3), (7, 5), (2, 2)]:
    MM[y][x] = 0
# float32 metres; 0 and negative = no reading. Values chosen not to be exact in float32.
M = [[round(0.4 + 0.013 * x + 0.021 * y + 0.0007 * x * y, 6) for x in range(W)] for y in range(H)]
for x, y in [(3, 3), (4, 3), (0, 5)]:
    M[y][x] = 0.0
M[1][6] = -0.5

DEPTH = {
    "mm": {"dtype": "uint16", "width": W, "height": H, "data": [v for row in MM for v in row]},
    "m": {"dtype": "float32", "width": W, "height": H, "data": [v for row in M for v in row]},
}
INTRINSICS = [500.0, 480.0, 3.5, 2.5]

DETECTIONS = [
    {"bbox": [0, 0, 4, 3], "class": "cup", "conf": 0.9},
    {"bbox": [3.5, 2, 4, 4], "class": "bowl", "conf": 0.6},
    {"bbox": [6, 4, 5, 5], "class": "cup", "conf": 0.75},
    {"bbox": [10, 10, 2, 2], "class": "cup", "conf": 0.95},
    {"bbox": [1, 1, 2, 2], "class": "plate", "conf": 0.3},
    {"bbox": [2.2, 0.7, 1.1, 3.6], "class": "spoon", "conf": 0.6},
]
MASKS = [
    {"bbox": [0, 0, 8, 6], "conf": 0.99, "rle": "48"},
    {"bbox": [5, 1, 2, 2], "conf": 0.8, "rle": "48"},
    {"bbox": [1.5, 2.5, 3, 3], "conf": 0.85, "rle": "48"},
]
GRASPS = [
    {"x": 2.5, "y": 1.5, "theta": 0.3, "width": 40, "quality": 0.7, "class": "cup", "conf": 0.9},
    {"x": 3.5, "y": 2.5, "theta": -1.2, "width": 75, "quality": 0.95, "class": "bowl", "conf": 0.6},
    {"x": 6.4, "y": 4.6, "theta": 2.0, "width": 55, "quality": 0.8, "class": "cup", "conf": 0.75},
    {"x": 20, "y": 1, "theta": 0.0, "width": 60, "quality": 0.99, "class": "cup", "conf": 0.95},
    {"x": 0.2, "y": 0.4, "theta": 1.0, "width": 30, "quality": 0.6},
    {"x": 5.5, "y": 3.5, "theta": 0.7, "width": 62, "quality": 0.85, "class": "bowl", "conf": 0.6},
    {"x": 1.49, "y": 4.51, "theta": 3.0, "width": 50, "quality": 0.85},
]


# Extra masks for the grasp-result cases: two copy a detection's box (as Grounded-SAM does).
GROUP_MASKS = [
    {"bbox": [3.5, 2, 4, 4], "conf": 0.7, "rle": "48"},
    {"bbox": [0, 0, 4, 3], "conf": 0.6, "rle": "48"},
]


def _index(items, obj):
    """Index of *obj* in *items* by identity (the helpers return the result's own objects)."""
    return next(i for i, x in enumerate(items) if x is obj)


def depth_array(name):
    d = DEPTH[name]
    return np.array(d["data"], dtype=d["dtype"]).reshape(d["height"], d["width"])


def det_result():
    return Result.from_json({"task": "detection", "model": "m", "detections": DETECTIONS})


def mask_result():
    return Result.from_json({"task": "segmentation", "model": "m", "masks": MASKS})


def grasps():
    return [Grasp.from_json(g) for g in GRASPS]


def num(v):
    """A float for JSON (None stays None)."""
    return None if v is None else float(v)


def build():
    """Every case with the Python SDK's answer, as the JSON object."""
    K = CameraIntrinsics(*INTRINSICS)
    out = {
        "_comment": "Generated by gen_postprocess_sync.py from the Python SDK; run by both SDKs' tests.",
        "depth": DEPTH,
        "intrinsics": INTRINSICS,
        "detections": DETECTIONS,
        "masks": MASKS,
        "grasps": GRASPS,
    }

    out["backproject"] = []
    for u, v, z in [(0, 0, 1.0), (3.5, 2.5, 0.8), (640, 480, 1.234), (-12.5, 7.25, 2.0), (100, -50, 0.0)]:
        out["backproject"].append({"u": u, "v": v, "z": z, "want": list(backproject(u, v, z, K)),
                                   "distance": camera_distance(u, v, z, K)})

    out["grasp_geometry"] = []
    for g in grasps():
        out["grasp_geometry"].append({"grasp": g.to_json(), "pose": g.pose, "contacts": g.contacts(),
                                      "contacts_flat": g.contacts_flat()})

    out["depth_at_detection"] = []
    for depth in ["mm", "m"]:
        for mode in ["median", "mean", "min", "max"]:
            for scale in [None, 0.002]:
                for size in [None, [16, 12]]:
                    for items in ["detections", "masks"]:
                        res = det_result() if items == "detections" else mask_result()
                        got = get_depth_at_detection(depth_array(depth), res, mode=mode, depth_scale=scale,
                                                     image_size=tuple(size) if size else None)
                        out["depth_at_detection"].append({"depth": depth, "items": items, "mode": mode,
                                                          "depth_scale": scale, "image_size": size,
                                                          "want": [num(v) for v in got]})

    out["object_distances"] = []
    for depth in ["mm", "m"]:
        for mode in ["median", "mean", "min", "max"]:
            for scale in [None, 0.0005]:
                for items in ["detections", "masks"]:
                    res = det_result() if items == "detections" else mask_result()
                    got = object_distances(depth_array(depth), res, INTRINSICS, mode=mode, depth_scale=scale)
                    out["object_distances"].append({"depth": depth, "items": items, "mode": mode,
                                                    "depth_scale": scale, "want": [num(v) for v in got]})

    out["grasp_distances"] = []
    for depth in ["mm", "m"]:
        for window in [0, 1, 2, 3]:
            for scale in [None, 0.01]:
                got = grasp_distances(depth_array(depth), grasps(), K, window=window, depth_scale=scale)
                out["grasp_distances"].append({"depth": depth, "window": window, "depth_scale": scale,
                                               "want": [num(v) for v in got]})

    # select_target_object: kwargs in Python names; "depth" names a DEPTH entry, "intrinsics" true = INTRINSICS.
    obj_cases = [
        {},
        {"cls": "cup"},
        {"cls": ["bowl", "plate"]},
        {"cls": "fork"},
        {"min_conf": 0.8},
        {"min_conf": 0.99},
        {"near_point": "center", "image_size": [8, 6]},
        {"near_point": [0, 0]},
        {"near_point": [7, 5], "cls": "cup"},
        {"weights": {"area": 1}},
        {"weights": {"conf": 1, "area": 1}},
        {"weights": {"conf": 2, "near": 1, "area": 0.5}, "near_point": [6, 1]},
        {"weights": {"conf": 0, "area": 0}},
        {"target_distance": 1.1, "depth": "mm", "intrinsics": True},
        {"target_distance": 1.3, "depth": "mm", "intrinsics": True, "mode": "max"},
        {"target_distance": 0.45, "depth": "m", "intrinsics": True, "distance_sigma": 0.01},
        {"target_distance": 2.2, "depth": "mm", "intrinsics": True, "depth_scale": 0.002},
        {"target_distance": 1.1, "depth": "mm", "intrinsics": True, "weights": {"distance": 1, "conf": 1}},
        {"target_distance": 1.1, "depth": "mm", "intrinsics": True, "near_point": [0, 0]},
        {"items": "masks"},
        {"items": "masks", "weights": {"area": 1}},
        {"items": "masks", "near_point": [6, 2]},
        {"items": "masks", "cls": "cup"},
        {"items": "masks", "target_distance": 0.5, "depth": "m", "intrinsics": True},
    ]
    out["select_target_object"] = []
    for case in obj_cases:
        kw = {k: v for k, v in case.items() if k != "items"}
        res = mask_result() if case.get("items") == "masks" else det_result()
        if "image_size" in kw:
            kw["image_size"] = tuple(kw["image_size"])
        if "near_point" in kw and isinstance(kw["near_point"], list):
            kw["near_point"] = tuple(kw["near_point"])
        if "depth" in kw:
            kw["depth_result"] = depth_array(kw.pop("depth"))
        if kw.pop("intrinsics", False):
            kw["intrinsics"] = INTRINSICS
        _, idx = select_target_object(res, return_index=True, **kw)
        out["select_target_object"].append({"kwargs": case, "want_index": idx})

    grasp_cases = [
        {},
        {"cls": "cup"},
        {"cls": ["bowl"]},
        {"cls": ""},
        {"gripper_min": 50},
        {"gripper_max": 50},
        {"gripper_min": 45, "gripper_max": 70},
        {"gripper_min": 100},
        {"target_point": [0, 0]},
        {"target_point": [6, 5], "cls": "cup"},
        {"gripper_min": 30, "gripper_max": 80, "weights": {"width": 1}},
        {"gripper_min": 30, "gripper_max": 80, "weights": {"width": 1, "quality": 2}},
        {"weights": {"quality": 1, "near": 1}, "target_point": [3, 3]},
        {"target_distance": 1.05, "depth": "mm", "intrinsics": True},
        {"target_distance": 1.25, "depth": "mm", "intrinsics": True, "window": 0},
        {"target_distance": 0.48, "depth": "m", "intrinsics": True, "distance_sigma": 0.02},
        {"target_distance": 1.05, "depth": "mm", "intrinsics": True, "weights": {"distance": 1, "quality": 1}},
        {"target_distance": 10.0, "depth": "mm", "intrinsics": True, "depth_scale": 0.01, "window": 1},
        {"weights": {"near": 1}},
    ]
    out["select_target_grasp"] = []
    for case in grasp_cases:
        kw = dict(case)
        if "target_point" in kw:
            kw["target_point"] = tuple(kw["target_point"])
        if "depth" in kw:
            kw["depth_result"] = depth_array(kw.pop("depth"))
        if kw.pop("intrinsics", False):
            kw["intrinsics"] = INTRINSICS
        _, idx = select_target_grasp(grasps(), return_index=True, **kw)
        out["select_target_grasp"].append({"kwargs": case, "want_index": idx})

    # Result.filter_grasps / group_by_class on one grasp result: kept grasps as indices into GRASPS.
    gres = Result.from_json({"task": "grasp", "model": "m", "detections": DETECTIONS,
                             "masks": MASKS + GROUP_MASKS, "grasps": GRASPS})
    gl = gres.grasps
    out["group_masks"] = GROUP_MASKS
    out["filter_grasps"] = []
    for k in [None, 0, 1, 2, 3]:
        kept = gres.filter_grasps(k).grasps
        out["filter_grasps"].append({"max_per_object": k, "want": [_index(gl, g) for g in kept]})
    for k in [1, 2]:  # no detections: class-agnostic grasps by mask box, class-aware by (class, conf)
        mres = Result.from_json({"task": "grasp", "model": "m", "masks": MASKS, "grasps": GRASPS})
        out["filter_grasps"].append({"max_per_object": k, "masks_only": True,
                                     "want": [_index(mres.grasps, g) for g in mres.filter_grasps(k).grasps]})
    out["group_by_class"] = {
        label: {"detections": [_index(gres.detections, d) for d in r.detections],
                "masks": [_index(gres.masks, m) for m in r.masks],
                "grasps": [_index(gl, g) for g in r.grasps]}
        for label, r in gres.group_by_class().items()
    }

    def check(o):  # JSON has no NaN / Infinity
        if isinstance(o, float):
            assert math.isfinite(o), o
        elif isinstance(o, dict):
            for v in o.values():
                check(v)
        elif isinstance(o, list):
            for v in o:
                check(v)

    check(out)
    return out


def main():
    out = build()
    path = Path(__file__).resolve().parent / "postprocess_sync.json"
    path.write_text(json.dumps(out, indent=1) + "\n")
    print("wrote", path, {k: len(v) for k, v in out.items() if isinstance(v, list)})


if __name__ == "__main__":
    main()
