"""Generate class_colors.json: the drawing colours and sizes of the Python SDK's draw()
(clients/python/visionserve/visualize.py), so the JS toSVG (clients/js/src/visualize.ts) picks the
same colour for a class and the same label / line sizes. Run by clients/js/tests/visualize.test.ts
and clients/python/tests/test_class_colors_sync.py. Regenerate after changing them on purpose:

    PYTHONPATH=clients/python python3 clients/testdata/gen_class_colors.py
"""

import json
from pathlib import Path

from visionserve.visualize import _CLASS_PALETTE, _PALETTE, _auto_sizes, _class_colour_map, _fnv1a, _text_colour

NAMES = ["dog", "bench", "person", "cat", "laptop", "carrot", "broccoli", "bowl", "cup", "car", "chair",
         "", "a", "Z", "élan", "猫", "traffic light", "dog."]
LISTS = [
    ["dog", "bench"],
    ["carrot", "broccoli", "bowl"],
    ["dog", "dog", "bench", "dog"],
    ["person", "dog", "bench", "cup", "car", "chair", "élan", "猫", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"],
    ["Zebra", "apple", "Apple", "zebra"],
    [],
]
SIZES = [[640, 426], [640, 480], [320, 240], [4000, 3000], [1920, 1080], [100, 50], [8, 8], [6000, 9000]]


def build():
    return {
        "_comment": "Generated by gen_class_colors.py from the Python SDK's draw(); run by both SDKs' tests.",
        "class_palette": [list(c) for c in _CLASS_PALETTE],
        "index_palette": [list(c) for c in _PALETTE],
        "fnv1a": [{"name": n, "hash": _fnv1a(n)} for n in NAMES],
        "class_colour": [{"name": n, "colour": list(_CLASS_PALETTE[_fnv1a(n) % len(_CLASS_PALETTE)])} for n in NAMES],
        "class_colour_map": [{"names": names, "colours": [[k, list(v)] for k, v in _class_colour_map(names).items()]}
                             for names in LISTS],
        "text_colour": [{"bg": list(c), "text": list(_text_colour(c))} for c in list(_CLASS_PALETTE) + list(_PALETTE) + [(255, 0, 0)]],
        "auto_sizes": [{"size": s, "font": f, "line": lw} for s in SIZES for f, lw in [_auto_sizes(*s)]],
    }


def main():
    path = Path(__file__).resolve().parent / "class_colors.json"
    path.write_text(json.dumps(build(), indent=1, ensure_ascii=False) + "\n")
    print("wrote", path)


if __name__ == "__main__":
    main()
