package preprocess_test

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"visionserve/internal/vision/preprocess"
)

var update = flag.Bool("update", false, "rewrite testdata/geometry_sync.json from the Go implementation")

// geometryCase is one row of testdata/geometry_sync.json: the tensor shape and Meta a spec gives
// for an image size. clients/python/tests/test_go_python_sync.py checks the converter's
// reference implementation (reference.apply_spec) against the same rows, so both sides compute
// the same geometry for every mode — the pixels themselves differ only by the resampler (PIL vs
// imaging), which tier B1 measures.
type geometryCase struct {
	Spec  map[string]any  `json:"spec"`
	Image [2]int          `json:"image"`
	Shape []int64         `json:"shape"`
	Meta  preprocess.Meta `json:"meta"`
}

// geometrySpecs are written in the manifest block's vocabulary (what Python reads).
var geometrySpecs = []map[string]any{
	{"resize": "squash", "width": 560, "height": 560},
	{"resize": "squash", "width": 512, "height": 384, "layout": "NHWC"},
	{"resize": "letterbox", "width": 384, "height": 384},
	{"resize": "letterbox", "width": 640, "height": 480},
	{"resize": "center_crop", "width": 224, "height": 224},
	{"resize": "center_crop", "width": 336, "height": 224},
	{"resize": "center_crop", "width": 224, "height": 224, "crop_pct": 0.875},
	{"resize": "center_crop", "width": 224, "height": 224, "crop_pct": 0.9655172},
	{"resize": "center_crop", "width": 320, "height": 240, "crop_pct": 0.9},
	{"resize": "keep_aspect", "width": 518, "height": 518, "multiple_of": 14},
	{"resize": "keep_aspect", "width": 384, "height": 512},
	{"resize": "top_left_pad", "width": 640, "height": 640},
	{"resize": "top_left_pad", "width": 640, "height": 480},
	{"resize": "long_side", "width": 1024, "height": 1024, "layout": "HWC"},
	{"resize": "long_side_pad", "width": 1024, "height": 1024},
	{"resize": "long_side_pad", "width": 960, "height": 960, "multiple_of": 32, "no_upscale": true},
	{"resize": "long_side_pad", "width": 320, "height": 240, "multiple_of": 32},
	{"resize": "none"},
}

var geometrySizes = [][2]int{{1, 1}, {3, 5}, {17, 31}, {640, 480}, {480, 640}, {2001, 999}, {999, 2001}}

func specFromMap(m map[string]any) preprocess.Spec {
	num := func(k string) int {
		if v, ok := m[k].(int); ok {
			return v
		}
		if v, ok := m[k].(float64); ok {
			return int(v)
		}
		return 0
	}
	s := preprocess.Spec{Resize: preprocess.Mode(fmt.Sprint(m["resize"])), Width: num("width"), Height: num("height"),
		MultipleOf: num("multiple_of")}
	if v, ok := m["crop_pct"].(float64); ok {
		s.CropPct = float32(v)
	}
	if v, ok := m["no_upscale"].(bool); ok {
		s.NoUpscale = v
	}
	if v, ok := m["layout"].(string); ok {
		s.Layout = preprocess.Layout(v)
	}
	return s
}

func TestGeometrySyncCorpus(t *testing.T) {
	if raceEnabled && !*update {
		t.Skip("pure geometry, ~100 resizes up to 1024²: checked by the normal (non -race) run")
	}
	var got []geometryCase
	for _, sm := range geometrySpecs {
		s := specFromMap(sm)
		for i, sz := range geometrySizes {
			ten, meta, err := s.Apply(nrgbaImage(sz[0], sz[1], int64(i)))
			if err != nil {
				t.Fatalf("%v %v: %v", sm, sz, err)
			}
			got = append(got, geometryCase{Spec: sm, Image: sz, Shape: ten.Shape, Meta: meta})
		}
	}
	path := filepath.Join("testdata", "geometry_sync.json")
	gotJSON, err := json.MarshalIndent(map[string]any{
		"_doc":  "Tensor shape + Meta of preprocess.Spec.Apply per (spec, image WxH). Generated by `go test ./internal/vision/preprocess -run GeometrySync -update`; read by clients/python/tests/test_go_python_sync.py.",
		"cases": got,
	}, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(gotJSON, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run with -update to create it)", err)
	}
	var want struct {
		Cases []geometryCase `json:"cases"`
	}
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatal(err)
	}
	if len(want.Cases) != len(got) {
		t.Fatalf("%d cases in %s, the implementation gives %d", len(want.Cases), path, len(got))
	}
	for i := range got {
		g, w := got[i], want.Cases[i]
		if fmt.Sprint(g.Shape) != fmt.Sprint(w.Shape) || g.Meta != w.Meta || g.Image != w.Image {
			t.Errorf("case %d %v %v: got %v %+v, corpus %v %+v", i, g.Spec, g.Image, g.Shape, g.Meta, w.Shape, w.Meta)
		}
	}
}
